name: Backend Code Style

on:
  # leaving here in case we need to also run it on pull requests (if we want to delete it on push for example)
  # pull_request:
  #   # branches: [ "main" ]
  #   paths-ignore:
  #     - 'frontend/**'
  push:
    # branches: [ "main" ]
    # tags: [ "*.*.*" ]
    paths:
      - 'backend/**'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v1

    - name: ✍  Check hlint and stylish
      run: |
        curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
        curl -sSL https://raw.github.com/jaspervdj/stylish-haskell/master/scripts/latest.sh | sh -s $(find . -type f -name "*.hs" ! -path "*.stack-work*") -i
        if [ -z "$(git status --porcelain)" ]; then
            echo "No style errors detected."
        else
            echo "Style errors detected:"
            git --no-pager diff
            exit 1
        fi
      # https://stackoverflow.com/questions/57806624/github-actions-how-to-build-project-in-sub-directory
      working-directory: backend
