name: Release

on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag you want to release'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.tag != '' }}
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.tag }}

    - name: 🖨 Print Context
      run: |
        cat README.md

    # - name: 🚀 Release
    #   uses: docker://antonyurchenko/git-release:latest
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     DRAFT_RELEASE: "false"
    #     PRE_RELEASE: "true"
    #     CHANGELOG_FILE: "CHANGELOG.md"
    #     ALLOW_EMPTY_CHANGELOG: "false"
    #     ALLOW_TAG_PREFIX: "true"
