name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v3

    - name: 🖨 Print Context
      run: |
        run: echo ${GITHUB_REF}

    - name: 🚀 Release
      uses: docker://antonyurchenko/git-release:v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        PRE_RELEASE: "true"
        CHANGELOG_FILE: "CHANGELOG.md"
        ALLOW_EMPTY_CHANGELOG: "false"
