name: Release

on:
  # Activate this by uncommenting push and pushing
  # Make sure that the env.GITHUB_REF is set correctly!!!
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_REF: 'refs/tags/v0.1.0'
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ env.GITHUB_REF }}

    # - name: 🖨 Print Context
    #   run: |
    #     cat README.md

    - name: 🚀 Release
      uses: docker://antonyurchenko/git-release:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        PRE_RELEASE: "true"
        CHANGELOG_FILE: "CHANGELOG.md"
        ALLOW_EMPTY_CHANGELOG: "false"
